name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        id: image_build
        run: |
          docker build -t dockerfile --iidfile=image_id.out .
          echo ::set-output name=image::docker

      - name: Run Uptycs vulnerability scanner
        uses: uptycslabs/uptycs-action@3.0.0
        with:
          image-id: ${{ steps.image_build.outputs.image }}
          # It's recommended to store the UPTYCS_CREDENTIALS as a secrets.
          #
          # See the section below on secrets management for additional
          # information.
          credentials: ${{ secrets.UPTYCS_CREDENTIALS }}
          output-format: json
          
      - name: Read Scan Output Summary
        id: read-scan-output
        shell: bash
        run: |
          OUTPUT_FILE="github-image-scan_vulnerabilities.json"
          ls -al
          
